INSERT INTO pages
    (name, description)
VALUES
    ("Croissants", "O croissant, é um tipo de massa folhada em formato de meia-lua. São consumidos no café da manhã em muitos países europeus e servidos como sobremesa em todo o mundo. Conheça nossas opcões de croissants salgados e doces."),
    ("Esfihas", "A esfiha é uma pequena torta assada originária da Síria e do Líbano, e encontrada em outros países do Oriente Médio. Conheça nossos produtos e faça seu pedido."),
    ("Nhoques", "O nhoque é um prato típico da cozinha italiana. Trata-se de uma massa cozida dividida em pequenas porções arredondadas, pode ser servida com o molho de preferência. Experimente mais essa delícia da Massas Chasko."),
    ("Pães de Queijo", "O pão de queijo é originário de Minas Gerais e surgiu por volta de 1750, usando polvilho de mandioca, queijo, ovos e leite. Conheça nossos produtos e faça seu pedido para experimentar essa delícia."),
    ("Pierogues", "Tradição dos imigrantes poloneses, o pierogue (ou 'pierog') é basicamente um pastel salgado cozido. Com uma massa saborosa recheios únicos, o produto tornou-se carro chefe da Massas Chasko por ser um dos mais procurados pelos consumidores."),
    ("Outros Produtos", "Também possuímos Charuto, Churros, Coxinha, Kibe, Macarrão, Hamburgão e Hot Dog. Conheça nossos produtos e faça seu pedido.");

INSERT INTO categories
    (name, weight, page_id)
VALUES
    ("Croissants", "350g", 1),
    ("Croissants", "1,2Kg", 1),
    ("Esfihas", "350g", 2),
    ("Esfihas", "1,2Kg", 2),
    ("Esfihas Abertas", "400g", 2),
    ("Nhoques", "400g", 3),
    ("Nhoques", "1Kg", 3),
    ("Pães de Queijo", "500g", 4),
    ("Pierogues", "400g", 5),
    ("Pierogues", "2Kg", 5),
    ("Mini Pierogues", "1Kg", 5),
    ("Outros Produtos", "400g", 6),
    ("Outros Produtos", "1Kg", 6),
    ("Outros Produtos", "1,2Kg", 6);

INSERT INTO products
    (name, category_id)
VALUES
    ("Croissant de Carne Moída", 1),
    ("Croissant de Frango", 1),
    ("Croissant de Pizza", 1),
    ("Croissant de Palmito", 1),
    ("Croissant de Banana com Canela", 1),
    ("Croissant de Chocolate Preto", 1),
    ("Croissant de Carne Moída", 2),
    ("Croissant de Frango", 2),
    ("Croissant de Pizza", 2),
    ("Croissant de Chocolate Preto", 2),
    ("Esfiha de Carne Moída", 3),
    ("Esfiha de Frango", 3),
    ("Esfiha de Pizza", 3),
    ("Esfiha de Palmito", 3),
    ("Esfiha de Costela", 3),
    ("Esfiha de Multigrãos", 3),
    ("Esfiha de Carne Moída", 4),
    ("Esfiha de Frango", 4),
    ("Esfiha Aberta de Carne Moída", 5),
    ("Esfiha Aberta de Frango", 5),
    ("Esfiha Aberta de Pizza", 5),
    ("Esfiha Aberta de Costela", 5),
    ("Esfiha Aberta de Chocolate Preto", 5),
    ("Nhoque Tradicional", 6),
    ("Nhoque Recheado de Carne Moída", 6),
    ("Nhoque Recheado de Frango", 6),
    ("Nhoque Recheado de Queijo", 6),
    ("Nhoque Tradicional", 7),
    ("Nhoque de Espinafre", 7),
    ("Nhoque Recheado de Carne Moída", 7),
    ("Nhoque Recheado de Frango", 7),
    ("Nhoque Recheado de Queijo", 7),
    ("Pão de Queijo com Cheddar", 8),
    ("Pão de Queijo com Vinagrete", 8),
    ("Pão de Queijo Tradicional", 8),
    ("Pierogue de Batata", 9),
    ("Pierogue de Batata e Bacon", 9),
    ("Pierogue de Batata e Frango", 9),
    ("Pierogue de Batata e Carne Desfiada", 9),
    ("Pierogue de Batata e Repolho", 9),
    ("Pierogue de Batata e Rúcula", 9),
    ("Pierogue de Calabresa", 9),
    ("Pierogue de Espinafre Ricota e Brócolis", 9),
    ("Pierogue de Feijão e Bacon", 9),
    ("Pierogue de Pizza", 9),
    ("Pierogue de Requeijão e Ricota", 9),
    ("Pierogue de Ricota com Tomate Seco", 9),
    ("Pierogue Tradicional", 9),
    ("Pierogue de Batata", 10),
    ("Pierogue de Batata e Bacon", 10),
    ("Pierogue de Batata e Frango", 10),
    ("Pierogue de Calabresa", 10),
    ("Pierogue de Requeijão e Ricota", 10),
    ("Pierogue Tradicional", 10),
    ("Mini Pierogue de Bacon", 11),
    ("Mini Pierogue de Calabresa", 11),
    ("Mini Pierogue de Carne Desfiada", 11),
    ("Mini Pierogue de Espinafre Ricota e Brócolis", 11),
    ("Mini Pierogue de Frango", 11),
    ("Mini Pierogue de Requeijão", 11),
    ("Mini Pierogue Tradicional", 11),
    ("Charuto de Repolho", 12),
    ("Churros de Doce de Leite com Chocolate", 12),
    ("Coxinha de Frango e Catupiry", 12),
    ("Kibe Recheado", 12),
    ("Macarrão Talharim", 12),
    ("Churros de Doce de Leite com Chocolate", 13),
    ("Coxinha de Frango e Catupiry", 13),
    ("Kibe Recheado", 13),
    ("Hamburgão", 14),
    ("Hot Dog", 14);